language: android
env:
  matrix:
    - ANDROID_TARGET=android-21  ANDROID_ABI=armeabi-v7a

android:
  components:
    - tools
    - android-21
    - build-tools-21.1.1
    - sys-img-armeabi-v7a-android-21
